// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/cuid/index.d.ts
declare module 'cuid' {
// Type definitions for cuid
// Project: https://github.com/ericelliott/cuid
// Definitions by: Dave Keen <http://www.keendevelopment.ch>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


function cuid(): string;

export = cuid
}
